@startuml Login
Actor ユーザー
Participant Frontend as Front
Participant Backend as Back
Participant Cognito

ユーザー --> Front: ユーザー情報入力
Front --> Back: Post: /login -body: {username, password, facility_code}
Back --> Cognito: ユーザー情報検証
Cognito --> Back: トークン返却
Back --> Front: トークン返却・Cookieに保存

@enduml
```