@startuml Login
Actor ユーザー
Participant Frontend as Front
Participant Backend as Back
Participant Cognito
Database Redis

ユーザー --> Front: ユーザー情報入力
Front --> Back: Post: /auth/login -body: {username, password, facility_code}
Back --> Cognito: ユーザー情報検証
Cognito --> Back: トークン返却
Back --> Redis: SessionID・トークン保存
Back --> Front: SessionId返却
Front --> Front: CookieにSessionIDを保存


@enduml
```