@startuml entity-relationship-diagram
skinparam linetype ortho

package 施設情報 {
  entity facilities
}

package 住所 {
  entity addresses {
    * binary address_id <<PK>>
    --
    int zip_code "郵便番号"
    string prefecture "住所"
    string city "市区町村"
    string address_line1 "町名"
    string address_line2 "番地"
    string latitude "緯度"
    string longitude "経度"
  }
}

package エリア {
  entity areas {
    * binary id <<PK>>
    --
    string area_code "地域エリア名"
    binary facility_id <<FK>> "施設ID"
  }

  entity areas_addresses {
    * binary id <<PK>>
    --
    binary area_id <<FK>> "エリアID"
    binary address_id <<FK>> "住所ID"
  }
}

addresses }o--o{ areas
areas }o--|| facilities


@enduml