@startuml entity-relationship-diagram
skinparam linetype ortho

package 経営データ {
  entity labor_management_item_names {
    * ulid id <<PK>>
    --
    string name "経営数値の項目名"
  }

  entity labor_management_items {
    * ulid id <<PK>>
    --
    ulid facility_id <<FK>> "施設ID"
    ulid monthly_labor_management_id <<FK>> "月次経営データID"
    ulid labor_management_item_name_id <<FK>> "経営数値の項目名ID"
    int data "データ"

  }

  note bottom of labor_management_items
  算出はサーバーで行い、計算されたデータのみを保存する
  end note

  entity manthry_labor_managements {
    * ulid id <<PK>>
    --
    ulid facility_id <<FK>> "施設ID"
    date month "月"
  }
}

package 施設情報 {
  entity facilities {
  }
}


manthry_labor_managements ||--o{ labor_management_items
manthry_labor_managements ||--|| facilities
labor_management_items }o--|| labor_management_item_names
labor_management_items ||--|| facilities

@enduml