@startuml entity-relationship-diagram
skinparam linetype ortho

package 経営データ {
  entity labor_management_item_names {
    経営数値の項目名
    id: binary(16) <<PK>>
    --
    facility_id: binary(16) <<FK>> "施設ID"
    name: string "項目名"
  }

  entity labor_management_items {
    経営数値の項目ごとのデータ
    id: binary(16) <<PK>>
    --
    monthly_labor_management_id: binary(16) <<FK>> "月次経営データID"
    labor_management_item_name_id: binary(16) <<FK>> "経営数値の項目名ID"
    data int "データの値"
  }

  note bottom of labor_management_items
  項目ごとにデータを保存し、月次経営データと紐づける
  end note

  entity monthly_labor_managements {
    月次経営データ
    id binary(16) <<PK>>
    --
    facility_id binary(16) <<FK>> "施設ID"
    staff_id binary(16) <<FK>> "職員ID"
    year_month date "年月"
  }
}

package 施設情報 {
  entity facilities {
  }
}

package 職員情報 {
  entity users {
  }
}


monthly_labor_managements ||--o{ labor_management_items
monthly_labor_managements ||--|| facilities
monthly_labor_managements ||--|| users
labor_management_items }o--|| labor_management_item_names
labor_management_item_names ||--|| facilities

@enduml