@startuml entity-relationship-diagram
skinparam linetype ortho

package 権限 {
  entity policies {
    id: binary(16) <<PK>>
    --
    string name "ポリシー名"
  }

  entity position_policies {
    id: binary(16) <<PK>>
    --
    position_id: binary(16) <<FK>> "役職ID"
    policy_id: binary(16) <<FK>> "ポリシーID"
  }
  note bottom of position_policies
    役職ごとに設定されるデフォルトの権限
    役職が追加・変更された際に、UserPolicyが上書きされる
  end note

  entity user_policies {
    id: binary(16) <<PK>>
    --
    staff_id: binary(16)  <<FK>> "ユーザーID"
    policy_id: binary(16) <<FK>> "ポリシーID"
  }
  note bottom of user_policies
    ユーザーが持っている権限
    認可にはこの情報を参照する
  end note

  entity user_policy_targets {
    id: binary(16) <<PK>>
    --
    user_policy_id: binary(16) <<FK>> "ユーザーポリシーID"
    target_user_id: binary(16) <<FK>> "ターゲットユーザーID"
  }
  note bottom of user_policy_targets
    特定のユーザーポリシーに関連するターゲットユーザーの管理
    例: カレンダーの閲覧対象ユーザー
  end note
}

package 職員情報 {
  entity users
}

package 施設情報 {
  entity positions
}

policies ||--o{ position_policies
policies ||--o{ user_policies
users ||--o{ user_policies
positions ||--o{ position_policies
user_policies ||--o{ user_policy_targets
users ||--o{ user_policy_targets
@enduml
