@startuml entity-relationship-diagram
skinparam linetype ortho

package 施設情報 {
  entity facilities
}

package 住所 {
  entity addresses {
    住所
    address_id: binary(16) <<PK>>
    --
    zip_code: int "郵便番号"
    prefecture: string "住所"
    city string: "市区町村"
    address_line1: string "番地までの住所"
    address_line2: string "建物名"
    latitude: string "緯度"
    longitude: string "経度"
  }
}

package エリア {
  entity areas {
    特定の住所の範囲をグループ化したもの
    id: binary(16) <<PK>>
    --
    area_code: string "地域エリア名"
    facility_id: binary(16) <<FK>> "施設ID"
  }

  entity areas_addresses {
    id: binary <<PK>>
    --
    area_id: binary(16) <<FK>> "エリアID"
    address_id: binary(16) <<FK>> "住所ID"
  }
}

addresses ||--o{ areas_addresses
areas ||--o{ areas_addresses
areas }o--|| facilities


@enduml