@startuml entity-relationship-diagram
skinparam linetype ortho
package 施設情報 {
  entity facilities {
    施設
    id: binary(16) <<PK>>
    --
    name: string "施設名"
    address_id: binary(16) <<FK>> "住所ID"
  }
  entity positions {
    役職
    id: binary(16) <<PK>>
    --
    name: string "役職名"
    facility_id: binary(16) <<FK>> "施設ID"
  }

  entity teams {
    チーム
    id: binary(16) <<PK>>
    --
    name: string "チーム名"
    facility_id: binary(16) <<FK>> "施設ID"
  }

  note bottom of positions
    1: マネージャー
    2: チームリーダー
    2: メンバー
  end note

  entity departments {
    部署
    id: binary(16) <<PK>>
    --
    name: string "部署名"
    facility_id: binary(16) <<FK>> "施設ID"
  }

  note bottom of departments
    1: 看護部
    2: リハビリ部
  end note
  facilities ||--o{ positions
  facilities ||--o{ teams
  facilities ||--o{ departments
}


@enduml