@startuml entity-relationship-diagram
skinparam linetype ortho

package 患者情報 {
  entity patients {
    患者情報
    patient_id binary(16) <<PK>>
    --
    name string
    service_code_id string "受けているサービス内容のID"
    preferred_datetime string "希望する日時"
    address_id binary(16)  <<FK>> "住所ID"
    preferred_gender string "希望する担当者の性別"
    staff_id binary(16) <<FK>> "主に担当している職員のID"
    facility_id binary(16) <<FK>> "施設ID"
  }
  note bottom of patients
  希望する日時は、午前・午後・指定なしの3つの選択肢がある
  end note
}

package 住所 {
  entity addresses
}

package 施設情報 {
  entity facilities
}

package 職員情報 {
  entity users
}

package 訪問情報 {
  entity service_codes
}

patients ||--|| facilities
patients ||--|| addresses
patients ||--|| service_codes
patients ||--|| users
@enduml