@startuml entity-relationship-diagram
skinparam linetype ortho

package 予定 {
  entity schedules {
    schedule_id : binary(16) <<PK>> "スケジュールID"
    --
    staff_id: binary(16) NOT_NULL "職員のID"
    title: string  "予定のタイトル"
    schedule_type_id: binary(16) NOT_NULL <<FK>> "予定の種類ID"
    recurring_schedule_id: binary(16) <<FK>> "繰り返し予定ID"
    visit_info_id: binary(16) <<FK>> "訪問情報ID"
    description: string "予定の説明"
    visit_date: date NOT_NULL "予定日（YYYY-MM-DD）"
    start_time: time NOT_NULL "開始時間（HH:MM）"
    end_time: time NOT_NULL "終了時間（HH:MM）"
    schedule_cancel_id: binary(16)"キャンセル予定のid(NULL_OK)"
    is_overtime_work: boolean NOT_NULL "時間外勤務か(default=false)"
  }

  entity schedule_types {
    schedule_type_id binary(16) <<PK>>
    --
    name string "予定のタイプ名"
  }

  note bottom of schedule_types
    1: 通常業務
    3: 訪問
  end note

  entity schedule_cancels {
    id: binary(16) <<PK>>
    --
    schedule_id: binary(16) <<FK>> "キャンセルされた予定ID"
    cancel_reason: string "キャンセル理由"
  }

  entity recurring_rules {
    recurring_rule_id (16) <<PK>> "繰り返しルールID"
    --
    frequency: int NOT_NULL "繰り返し頻度（monthly, weekly)をenumで扱う"
    day_of_week: int "曜日"
    day_of_month: int "月の日"
    week_of_month: int "月の週"
    start_date: date NOT_NULL "開始日"
    end_date: date "終了日"
  }
  note top of recurring_rules
  月, 週のいずれかで、日付 or 第何週目の曜日かを指定する
  月：day_of_month
  週：week_of_month, day_of_week
  end note

  entity recurring_schedules {
    recurring_schedule_id: binary(16) <<PK>> NOT_NULL
    --
    recurring_rule_id: binary(16) NOT_NULL "繰り返しルールID"
    schedule_type_id: binary(16) NOT_NULL "予定タイプID"
    visit_info_id: binary(16) "訪問情報ID"
    title: string "タイトル"
    description: string "説明"
    visit_date: date NOT_NULL"訪問日"
    start_time: time NOT_NULL "開始時間"
    end_time: time NOT_NULL "終了時間"
    recurring_exclusion_dates: json "除外日のリスト"
  }
  note top of recurring_schedules
    繰り返し予定の情報を保存する
    繰り返しタイプに基づいて、フロント側で予定を複製する
  end note
}


package 職員情報 {
  entity users {
  }
}

package 訪問情報 {
  entity visit_infos {
  }

}

schedules }o--|| users
schedules }o--|| schedule_types
schedules ||--o| schedule_cancels
schedules ||--o| visit_infos
recurring_schedules }o--|| users
recurring_schedules }o--|| schedule_types
recurring_schedules ||--|| recurring_rules
recurring_schedules ||--|| visit_infos

@enduml