@startuml entity-relationship-diagram
skinparam linetype ortho

package 予定 {
  entity schedules {
    * binary schedule_id <<PK>>
    --
    binary user_id "ユーザーID"
    string title "予定のタイトル（NULL_OK)"
    binary schedule_type_id <<FK>> "予定の種類"
    binary recurring_schedule_id <<FK>>"繰り返し予定ID（NULL_OK)"
    binary visit_info_id <<FK>> "訪問情報ID(NULL_OK)"
    string description "予定の説明(NULL_OK)"
    datetime visit_date "予定日（YYYY-MM-DD）"
    datetime start_time "開始時間（HH:MM）"
    datetime end_time "終了時間（HH:MM）"
    boolean is_cancelled"キャンセルされたかどうか(default=false)"
    boolean is_overtime_work "時間外勤務か(default=false)"
    datetime before_change_date "変更前の訪問日（YYYY-MM-DD"
    datetime before_change_start_time "変更前の開始時間（HH:MM）"
  }

  note bottom of schedules
    繰り返し予定で特定の予定のみ変更された場合、
    このテーブルに新しいレコードを追加する
    その際に、繰り返し予定のIDと変更前の日時を保存する
  end note

  entity schedule_types {
    * binary schedule_type_id <<PK>>
    --
    string name "予定のタイプ名"
  }

  note bottom of schedule_types
    1: 通常業務
    3: 訪問
  end note

  entity schedule_cancels {
    * binary id <<PK>>
    --
    binary schedule_id <<FK>> "キャンセルされた予定ID"
    string cancel_reason "キャンセル理由"
    datetime cancel_date "キャンセル日時"
  }

  entity recurring_rules {
    binary recurring_rule_id <<PK>>
    --
    binary schedule_id: スケジュールID <<FK>>
    int frequency: "繰り返し頻度（monthly, weekly)"
    int day_of_week: "曜日"
    int day_of_month: "月の日"
    int week_of_month: "月の週"
    datetime start_date: "開始日"
    datetime end_date: "終了日"
  }
  note top of recurring_rules
  繰り返し予定のルールを定義する
  end note

  entity recurring_schedules {
    binary recurring_schedule_id <<PK>>
    --
    binary recurring_rule_id: "繰り返しルールID"
    binary schedule_type_id: "予定タイプID"
    binary visit_info_id: "訪問情報ID"
    binary schedule_category_id: "予定カテゴリID"
    string title: "タイトル"
    string description: "説明"
    datetime visit_date: "訪問日"
    datetime start_time: "開始時間"
    datetime end_time: "終了時間"
  }
  note top of recurring_schedules
    繰り返し予定の情報を保存する
    繰り返しタイプに基づいて、フロント側で予定を複製する
  end note
}

package 住所 {
  entity addresses
}

package 職員情報 {
  entity users {
  }
}

package 患者情報 {
  entity patients {
  }
}

package 訪問情報 {
  entity visit_infos {
  }
  entity service_codes {
  }
  entity routes {
  }
}

schedules }o--|| users
schedules ||--o| schedule_cancels
schedules ||--|| schedule_rules
schedules }|--o| recurring_schedules
schedules ||--o| visit_infos
recurring_schedules ||--o{ schedules
recurring_schedules ||--|| recurring_rules
recurring_schedules ||--|| visit_infos
visit_infos ||--|| service_codes
visit_infos ||--|| patients
visit_infos ||--|| routes
routes ||--|{ addresses

@enduml