@startuml entity-relationship-diagram
skinparam linetype ortho

entity cognito_users {
  Cognitoに保存されているユーザー情報（DBには保存しない）
  username: string "ユーザー名"
  --
  phone_number: string "電話番号"
  email: string "メールアドレス"
  area_id: binary(16) <<FK>> "担当エリアID"
  position_id: binary(16) <<FK>> "役職ID"
  team_id: binary(16) <<FK>> "チームID"
}

package 職員情報 {
  entity users {
    id binary(16) NOT_NULL <<PK>> "CognitoのユーザーID"
    --
    username: string NOT_NULL "ユーザー名"
    phone_number: string "電話番号"
    email: string "メールアドレス"
    gender: string NOT_NULL  "性別"
    facility_id: binary(16) <<FK>> "施設ID"
    area_id: binary(16) <<FK>> "担当エリアID"
    position_id: binary(16) NOT_NULL <<FK>> "役職ID"
    department_id: binary(16) NOT_NULL <<FK>> "部署ID"
    team_id: binary(16) NOT_NULL <<FK>> "チームID"
  }

  note bottom of users
    性別は、男性・女性・の2つの選択肢がある
    1. 男性
    2. 女性
  end note

  entity monthly_workings {
    職員に紐づく予定データから算出した月次の稼働時間
    working_data_id binary(16) <<PK>>
    --
    user_id binary(16) <<FK>>
    year_month date "稼働時間の年月"
    monthly_visit_count int "月の訪問回数"
    work_hours int "勤務時間"
  }
}

package エリア {
  entity areas
}

package 施設情報 {
  entity facilities
  entity teams
  entity positions
  entity departments
}

cognito_users ||--|| users
users ||--|| positions
users ||--|| departments
users ||--o{ monthly_workings
users ||--|| facilities
users ||--|| teams
users ||--|| areas

@enduml
