@startuml entity-relationship-diagram
skinparam linetype ortho
!include facilities.puml

entity auth_users {
  * string username "ユーザー名"
  --
  string phone_number "電話番号"
  string password "パスワード"
  binaly facility_id <<FK>> "施設ID"
  binaly sub "一意のユーザーを特定するためのuuid"
}

note bottom of auth_users
  Cognitoのユーザー
  DBにも保存しない
end note

package 職員情報 {
  entity users {
    * binaly id <<PK>>
    --
    binary auth_user_id <<FK>> "CognitoユーザーID"
    string username "ユーザー名"
    string phone_number "電話番号"
    ENUM('男性', '女性') gender "性別"
    binary area_id <<FK>> "担当エリアID"
    binary position_id <<FK>> "役職ID"
    binary team_id <<FK>> "チームID"
    binary working_hours_id "月稼働時間ID"
    date created_at
    date updated_at
  }

  note bottom of users
    性別は、男性・女性・の2つの選択肢がある
    1. 男性
    2. 女性
  end note

  entity monthly_workings {
    * binary working_data_id <<PK>>
    --
    binary user_id <<FK>>
    date month "稼働時間の月"
    int monthly_visit_count "月の訪問回数"
    int work_hours "勤務時間"
  }
}

package エリア {
  entity areas
}

package 施設情報 {
  entity facilities
  entity teams
  entity positions
  entity departments
}

auth_users ||--|| users
users ||--|| positions
users ||--|| departments
users ||--o{ monthly_workings
users ||--|| facilities
users ||--|| teams
users ||--|| areas

@enduml
